### ISSUE TITLE
Investigate why PostgresPoolIT was randomly fine either on JVM or Native

### ISSUE THREAD

**Issue by Sgitario** [quarkus-qe/quarkus-test-suite#194]
On the repository, we had to rewrite the PostgresPoolIT to PostgresPoolTest because the scenario was randomly failing (see https://github.com/quarkus-qe/quarkus-test-suite/pull/191/commits/f653c4b8bd7278cd838423f49a222e3ae747e492).

The PostgresPoolTest test is now as it's in Beefy TS: https://github.com/quarkus-qe/beefy-scenarios/blob/main/303-quarkus-vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresPoolTest.java

This was done as a matter of urgency because the CI pipelines was randomly failing, either on JVM or Native (not always failing...).

My guess is that we are ticking to the [back pressure](https://vertx.io/docs/vertx-reactive-streams/java/) issue at test side as we're sending a lot of requests and at the same time, getting more network ++ database requests to validate the scenario. Using @QuarkusTest makes the test more stable because it avoids using the network to validate the scenario, it goes directly to the database pool.

**Comment by pjgg** [comment]
I could not reproduce the issue locally (and I would like to see the error in order to know more about this issue). 

But in my opinion, is not a problem with "QuarkusScenario Vs QuarkusTest ". The main difference is the implementation of the test itself: 
- In beefyScenarios there are two DB pools. One for the application and the other used by the test itself.
- In quarkus-test-suite there is only one DB pool (the application pool), also used by the test itself through a RestAPI. This second approach demands more resources because the test itself is very stressful but now also we have to check the status of DB pool per query with the same DB pool. 

The `Quarkus-test-suite` in pseudo-code looks like this:

```
Do {
      make Get Airlines RestQuery
      make GET DbActiveConnection RestQuery -> must be greater than 1 (because we have an IDLE, so the connections should expire but in the short-term of period (3ms) we should have more than 1 connection)
       
}Loop 25000

Wait until all events have been processed (is implemented with reactive style)
Make Get that makes a simple query to the DB as `SELECT CURRENT_TIMESTAMP` and then return activeConnections
Verify that there is only one activeConection (`SELECT CURRENT_TIMESTAMP`) IF there is more than one is because IDLE doesn't works

```

AS I said in my local environment always works (I have run the test more than 5 times), but In my opinion this implementation is dangerous because every time that you use a DB connection the IDLE timeout is reset so, If you are using the same DB pool for the application and also to check the status of the pool, I think that you could fall in some run conditions. 

Anyway I will run this test in CI (Jenkins) just to see if I can see the error.

**Comment by rsvoboda** [comment]
@pjgg any update on this?

**Comment by pjgg** [comment]
This issue was fixed. 

Basically, we were making so many requests/per second as is explained above (we were using the app API also to verify the DB status per transaction). 

The result was a connection refuse from an App point of view(in jenkins):

```
17:16:40 io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:3038
17:16:40 Caused by: java.net.ConnectException: Connection refused
```

This issue could be closed,
