### ISSUE TITLE
Review and remove usage of @QuarkusTest

### ISSUE THREAD

**Issue by mjurc** [quarkus-qe/quarkus-test-suite#226]
There are still some tests that use `@QuarkusTest` rather than `@QuarkusScenario`. Review these tests and reimplement them with new framework.

**Comment by rsvoboda** [comment]
```
for i in `git grep -l io.quarkus.test.junit.QuarkusTest`; do
  echo "$i"
  git blame $i | grep 'io.quarkus.test.junit.QuarkusTest';
  echo ""
done
http/http-minimum-reactive/src/test/resources/HelloResourceTest.java.template
9d347de6 (Kyrylo Shpak 2021-11-18 14:37:44 +0100  6) import io.quarkus.test.junit.QuarkusTest;

http/http-minimum-reactive/src/test/resources/NoFunctionalTest.java.template
9d347de6 (Kyrylo Shpak 2021-11-18 14:37:44 +0100  7) import io.quarkus.test.junit.QuarkusTest;

http/http-minimum/src/test/resources/HelloResourceTest.java.template
1646e552 (Jose 2021-05-21 10:46:26 +0200  6) import io.quarkus.test.junit.QuarkusTest;

http/http-minimum/src/test/resources/NoFunctionalTest.java.template
3575ad8d (Jose 2021-08-06 08:05:48 +0200  7) import io.quarkus.test.junit.QuarkusTest;

http/vertx-web-client/src/test/java/io/quarkus/qe/vertx/webclient/PureVertxHttpClientTest.java
3d0d3dcc (pablo gonzalez granados 2022-02-14 17:29:41 +0100 14) import io.quarkus.test.junit.QuarkusTest;

qute/multimodule/qute-test/src/test/java/io/quarkus/qe/qute/LocalizedMessagesTest.java
fc26839f qute/multimodule/qute-test/src/test/java/io/quarkus/qe/qute/ExampleResourceTest.java   (Fedor Dudinskiy         2022-01-11 10:49:43 +0100 11) import io.quarkus.test.junit.QuarkusTest;

security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/SecurityTest.java
a4fb584d (Josef Smrcka 2022-01-04 09:59:54 +0100 11) import io.quarkus.test.junit.QuarkusTest;

security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/SecurityTestProfile.java
a4fb584d (Josef Smrcka 2022-01-04 09:59:54 +0100  5) import io.quarkus.test.junit.QuarkusTestProfile;

spring/spring-data/src/test/java/io/quarkus/ts/spring/data/di/SpringDiIT.java
90f573fd spring/spring-data-primitive-types/src/test/java/io/quarkus/ts/spring/data/primitivetypes/di/SpringDiIT.java (Josef Smrcka 2021-07-27 14:52:03 +0200  17) import io.quarkus.test.junit.QuarkusTest;

sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/dbpool/AgroalPoolTest.java
1edabf6e (Jose 2021-07-28 09:40:44 +0200  28) import io.quarkus.test.junit.QuarkusTest;

sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/dbpool/AgroalTestProfile.java
1edabf6e (Jose 2021-07-28 09:40:44 +0200  8) import io.quarkus.test.junit.QuarkusTestProfile;

sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresPoolTest.java
a0c772c4 sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresPoolTest.java (Jose                    2021-08-18 15:12:46 +0200  23) import io.quarkus.test.junit.QuarkusTest;

sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresqlTestProfile.java
a0c772c4 (Jose 2021-08-18 15:12:46 +0200  6) import io.quarkus.test.junit.QuarkusTestProfile;

test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ConsumerPactTest.java
d9692c62 (Fedor Dudinskiy 2021-09-07 08:50:23 +0200 12) import io.quarkus.test.junit.QuarkusTest;

test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ProviderPactTest.java
d9692c62 (Fedor Dudinskiy 2021-09-07 08:50:23 +0200  8) import io.quarkus.test.junit.QuarkusTest;
```

**Comment by rsvoboda** [comment]
qute module is addressed in https://github.com/quarkus-qe/quarkus-test-suite/pull/557

**Comment by michalvavrik** [comment]
Review done, IMHO we should keep them all. Please feel free to reopen issue with updated description regarding expectations:

> http/http-minimum-reactive/src/test/resources/HelloResourceTest.java.template
9d347de61 (Kyrylo Shpak 2021-11-18 14:37:44 +0100  6) import io.quarkus.test.junit.QuarkusTest;

keep - this is DEV mode test template that needs `@QuarkusTest`

> http/http-minimum-reactive/src/test/resources/NoFunctionalTest.java.template
9d347de61 (Kyrylo Shpak 2021-11-18 14:37:44 +0100  7) import io.quarkus.test.junit.QuarkusTest;

keep - this is DEV mode test template that needs `@QuarkusTest`

> http/http-minimum/src/test/resources/HelloResourceTest.java.template
1646e552c (Jose 2021-05-21 10:46:26 +0200  6) import io.quarkus.test.junit.QuarkusTest;

keep - this is DEV mode test template that needs `@QuarkusTest`

> http/http-minimum/src/test/resources/NoFunctionalTest.java.template
3575ad8d5 (Jose 2021-08-06 08:05:48 +0200  7) import io.quarkus.test.junit.QuarkusTest;

keep - this is DEV mode test template that needs `@QuarkusTest`

> http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/PureVertxHttpClientTest.java
3d0d3dcc0 http/vertx-web-client/src/test/java/io/quarkus/qe/vertx/webclient/PureVertxHttpClientTest.java      (pablo gonzalez granados 2022-02-14 17:29:41 +0100 14) import io.quarkus.test.junit.QuarkusTest;

keep - Intention is to verify the webclient works with `@QuarkusTest`, the test name `io.quarkus.ts.http.vertx.webclient.PureVertxHttpClientTest#quarkusTestFipsVertxHttpClient` literally contains `quarkusTest` and we have `VertxWebClientIT` that uses `@QuarkusScenario`.
The PR that introduced test also mentions this intention https://github.com/quarkus-qe/quarkus-test-suite/pull/534.


> lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/AlphabeticallyFirstTest.java
2381cafde (Fedor Dudinskiy 2023-01-05 18:41:30 +0100  9) import io.quarkus.test.junit.QuarkusTest;

keep - Tests combination of `QuarkusTest` and `QuarkusTestMain` - https://issues.redhat.com/browse/QUARKUS-2789

> security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/SecurityTest.java
a4fb584d9 (Josef Smrcka 2022-01-04 09:59:54 +0100 11) import io.quarkus.test.junit.QuarkusTest;

keep - @TestSecurity only works with @QuarkusTest - https://issues.redhat.com/browse/QUARKUS-1584

> security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/SecurityTestProfile.java
a4fb584d9 (Josef Smrcka 2022-01-04 09:59:54 +0100  5) import io.quarkus.test.junit.QuarkusTestProfile;

keep - see above

> security/bouncycastle-fips/bcFipsJsse/src/test/java/io/quarkus/ts/security/bouncycastle/fips/jsse/BouncyCastleFipsJsseIT.java
bcba925b9 security/bouncycastle-fips/bcFipsJsse/src/test/java/io/quarkus/ts/security/bouncycastle/fips/BouncyCastleFipsJsseIT.java      (pablo gonzalez granados 2022-05-06 12:18:30 +0200  21) import io.quarkus.test.junit.QuarkusTest;

keep - point here is to test that BouncyCastleFips and Jsse Providers configured by Quarkus are available and Vertx can use them - so we need to inject Vertx.

> spring/spring-data/src/test/java/io/quarkus/ts/spring/data/di/SpringDiTest.java
90f573fd4 spring/spring-data-primitive-types/src/test/java/io/quarkus/ts/spring/data/primitivetypes/di/SpringDiIT.java (Josef Smrcka            2021-07-27 14:52:03 +0200  18) import io.quarkus.test.junit.QuarkusTest;

keep - please see comment `Not converted into @QuarkusScenario, because invoking jakarta.enterprise.inject.spi.CDI / io.quarkus.arc.Arc is not supported.`. I opened https://github.com/quarkus-qe/quarkus-test-suite/issues/1181 for this.

> sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/dbpool/AgroalPoolTest.java
1edabf6e9 sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/dbpool/AgroalPoolTest.java (Jose                    2021-07-28 09:40:44 +0200  27) import io.quarkus.test.junit.QuarkusTest;

keep - requires injection of EntityManager and AgroalDataSource. We could run test logic inside of endpoints and just query them, but IMO this is sensitive change as we test something happens after timeout etc. so ideally we need to have response right after Thread sleep is over. Adding there REST calls could make the tests flaky.

> sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/dbpool/AgroalTestProfile.java
1edabf6e9 sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/dbpool/AgroalTestProfile.java (Jose                    2021-07-28 09:40:44 +0200  8) import io.quarkus.test.junit.QuarkusTestProfile;

keep - please see above

> sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/dbpool/PostgresPoolTest.java
a0c772c4f sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresPoolTest.java (Jose                    2021-08-18 15:12:46 +0200  24) import io.quarkus.test.junit.QuarkusTest;

keep - please see reasoning about `AgroalPoolTest`

> sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/dbpool/PostgresqlTestProfile.java
a0c772c4f sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresqlTestProfile.java (Jose          2021-08-18 15:12:46 +0200  6) import io.quarkus.test.junit.QuarkusTestProfile;

keep - please see reasoning about `AgroalPoolTest`

> test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ConsumerPactTest.java
d9692c62d (Fedor Dudinskiy 2021-09-07 08:50:23 +0200 12) import io.quarkus.test.junit.QuarkusTest;

keep - here we want to test `@QuarkusTest` with Pact (`@PactTestFor` etc.).

> test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ProviderPactTest.java
d9692c62d (Fedor Dudinskiy   2021-09-07 08:50:23 +0200  9) import io.quarkus.test.junit.QuarkusTest;

keep - please see above

**Comment by rsvoboda** [comment]
Thanks for the detailed review report!
